name = "Modified Cobblemon Overclocked"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f06633c99bac49ed19368c12e7f18c9356961d5704d3dcf1ec0196b95650a890"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"

[export]
[export.curseforge]
project-id = 1206395

[options]
acceptable-game-versions = ["1.21.1"]
