name = "Modified Cobblemon Overclocked"
version = "1.8.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbd93b4c5b349c5368eb4549b77927982dc59ad0aeeb2e49332445cb76505b96"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"

[export]
[export.curseforge]
project-id = 1206395

[options]
acceptable-game-versions = ["1.21.1"]
