name = "Modified Cobblemon Overclocked"
version = "1.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2d85a1a1fd19cafe76700993a4eac49bf0bf1f8b04adb6f63f58223c06e86e2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.203"

[export]
[export.curseforge]
project-id = 1206395

[options]
acceptable-game-versions = ["1.21.1"]
