name = "Modified Cobblemon Overclocked"
version = "1.8.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebcc0008848f0c97179936d6e4ac28572e62b6820adbe47916890142586a5e08"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"

[export]
[export.curseforge]
project-id = 1206395

[options]
acceptable-game-versions = ["1.21.1"]
