name = "Modified Cobblemon Overclocked"
version = "1.8.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2a7a98ff601e792e8183e04aa5467e93417a0b6fc1fd66f9acf8e5fc6cfbdc7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"

[export]
[export.curseforge]
project-id = 1206395

[options]
acceptable-game-versions = ["1.21.1"]
