ServerEvents.recipes(event=> {
  event.remove({output: "lightmanscurrency:coinmint"})
  event.remove({mod: "lightmanscurrency", output: "lightmanscurrency:coin_copper"})
  event.remove({mod: "lightmanscurrency", output:  "lightmanscurrency:coin_iron"})
  event.remove({mod: "lightmanscurrency", output:  "lightmanscurrency:coin_gold"})
  event.remove({mod: "lightmanscurrency", output:  "lightmanscurrency:coin_emerald"})
  event.remove({mod: "lightmanscurrency", output:  "lightmanscurrency:coin_diamond"})
  event.remove({mod: "lightmanscurrency", output:  "lightmanscurrency:coin_netherite"})
  event.remove({output: "ars_nouveau:ritual_sunrise"})
  event.remove({output: "ars_nouveau:ritual_cloudshaping"})
  event.remove({output: "ars_nouveau:ritual_moonfall"})
  event.remove({output: "ars_additions:ritual_chunk_loading"})
  event.remove({output: "ars_additions:unstable_reliquary"})
  event.remove({output: "ars_nouveau:stable_warp_scroll"})
})
