#General settings
[general]
#modpackProjectID is now deprecated and will be removed soon
# Default: 0
# Range: > 0
modpackProjectID = 1206395
#The name of the modpack
modpackName = "Modified_Cobblemon_Overclocked"
#The version of the modpack
modpackVersion = "1.8.4"
#Use the metadata.json to determine the modpack version
#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
useMetadata = false
